[package]
name = "invent-tower"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
tokio = { version = "1.39.2", features = ["full"] }

[features]
default = ["stask"]
stask = []
atask = []
